# This is a basic workflow to help you get started with Actions

name: CI

on:
    workflow_dispatch:
    push:
        branches:
            - master

jobs:
    release:
        name: Create Release
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Checkout main
              id: checkout
              uses: actions/checkout@v2

            - name: Test tsc Build
              id: build
              run: |
                  npm install
                  npm run build

            - name: Get build date
              id: get_date
              run: echo "::set-output name=date::$(date +'%Y%m%d%H%M%S')"

            - name: Get version from package.json
              id: get_version
              uses: notiz-dev/github-action-json-property@release
              with:
                  path: 'package.json'
                  prop_path: 'version'

            - name: Create GitHub Release
              id: make_release
              uses: ncipollo/release-action@v1.10.0
              with:
                  tag: v${{steps.get_version.outputs.prop}}-${{steps.get_date.outputs.date}}
                  generateReleaseNotes: true
                  token: ${{ secrets.GITHUB_TOKEN }}
